version: "2"
services:

  kibana:
    image: kibana
    ports:
     - 5601:5601
    depends_on:
     - elasticsearch
    networks:
     - elk
    restart: always

  elasticsearch:
    image: elasticsearch
    ports:
     - 9200:9200 
    volumes:
     - /var/esdata:/usr/share/elasticsearch/data
    restart: always
    networks:
     - elk

networks:

  elk:
    driver: bridge
